insert into clients (created_by, created_when, full_name, phone)
values ('initial script', now(), 'Vasiliy Shishkin', '+79654741234'),
       ('initial script', now(), 'Емельянова Анна Викторовна', '+79384098403'),
       ('initial script', now(), 'Львов Марк Вячеславович', '+79169729443'),
       ('initial script', now(), 'Маркина Дарья Давидовна', '+79112213553'),
       ('initial script', now(), 'Васильева Вероника Николаевна', '+79117070026'),
       ('initial script', now(), 'Золотова София Александровна', '+79329270668'),
       ('initial script', now(), 'Тихонова Карина Владимировна', '+79612314093'),
       ('initial script', now(), 'Родина Дарья Давидовна', '+79082837874'),
       ('initial script', now(), 'Егоров Артём Даниилович', '+79605234417'),
       ('initial script', now(), 'Семенов Демид Максимович', '+79286184564'),
       ('initial script', now(), 'Алексеева София Фёдоровна', '+79014914962'),
       ('initial script', now(), 'Елизаров Дмитрий Владиславович', '+79974500996'),
       ('initial script', now(), 'Андреева Дарья Данииловна', '+79946649763'),
       ('initial script', now(), 'Зубкова Полина Алексеевна', '+79868451631'),
       ('initial script', now(), 'Кулагин Матвей Лукич ', '+79176435507'),
       ('initial script', now(), 'Фадеева Александра Захаровна', '+79336362968'),
       ('initial script', now(), 'Васильев Леонид Борисович', '+79542822651'),
       ('initial script', now(), 'Евдокимов Алексей Матвеевич', '+79999060271'),
       ('initial script', now(), 'Корнеев Матвей Даниилович', '+79774258602'),
       ('initial script', now(), 'Воробьев Гордей Андреевич', '+79102122402'),
       ('initial script', now(), 'Судаков Александр Михайлович', '+79416496633');

insert into employees_positions(title, description, role)
values ('jeweller', 'ordinary employee, authorized to create and view client orders', 'user'),
       ('manager', 'authorized for all user actions, plus all other actions', 'manager'),
       ('director', 'director can create and delete all', 'director');

insert into employees (created_by, created_when, login, password, full_name, phone, address,
                       birth_date, position_id)
values ('initial script', now(), 'mahala', 'CHANGE_ME', 'Александрова Майя Викторовна', '622-738-9223',
        'Брянская область, город Люберцы, шоссе Славы, 42', '1978-01-23', 1),
       ('initial script', now(), 'jori', 'CHANGE_ME', 'Матвеева Виолетта Даниловна', '488-478-8998',
        'Курганская область, город Истра, ул. Гоголя, 09', '1963-08-24', 1),
       ('initial script', now(), 'mateo', 'CHANGE_ME', 'Фомин Егор Богданович', '145-677-5126', 'Омская область, город Видное, въезд Славы, 58',
        '1956-12-22', 1),
       ('initial script', now(), 'stanislaus', 'CHANGE_ME', 'Олейников Михаил Эмильевич', '350-362-2352',
        'Читинская область, город Серпухов, пл. Бухарестская, 39', '1981-07-26', 1),
       ('initial script', now(), 'meta', 'CHANGE_ME', 'Беляева Ульяна Ильинична', '847-855-6253', 'Псковская область, город Можайск, наб. Косиора, 80',
        '1966-10-07', 1),
       ('initial script', now(), 'latrena', 'CHANGE_ME', 'Попова Алиса Мироновна', '368-851-4741',
        'Калужская область, город Дорохово, пр. Косиора, 49', '1998-11-15', 1),
       ('initial script', now(), 'jakie', 'CHANGE_ME', 'Меркулова Арина Максимовна', '908-938-5747', 'Иркутская область, город Можайск, ул. Ладыгина, 50',
        '1964-09-09', 1),
       ('initial script', now(), 'lil', 'CHANGE_ME', 'Короткова Анна Даниловна', '966-196-9201', 'Орловская область, город Люберцы, пер. Гагарина, 72',
        '1974-01-12', 1),
       ('initial script', now(), 'griz', 'CHANGE_ME', 'Горелов Матвей Егорович', '420-334-3412', 'Ульяновская область, город Талдом, шоссе Ленина, 05',
        '1977-03-20', 1),
       ('initial script', now(), 'ansell', 'CHANGE_ME', 'Агапова Мадина Даниэльевна', '312-328-1376', 'Ростовская область, город Балашиха, спуск Славы, 11',
        '1981-07-20', 1),
       ('initial script', now(), 'catriona', 'CHANGE_ME', 'Егоров Мирон Иванович', '930-908-1631',
        'Костромская область, город Серебряные Пруды, пр. Бухарестская, 85', '1985-05-19', 1),
       ('initial script', now(), 'louise', 'CHANGE_ME', 'Громова Ярослава Давидовна', '954-656-7989', 'Ивановская область, город Солнечногорск, въезд Гоголя, 98',
        '1974-10-21', 1),
       ('initial script', now(), 'evita', 'CHANGE_ME', 'Иванова Надежда Максимовна', '830-164-5294',
        'Новосибирская область, город Луховицы, пр. Космонавтов, 20', '1969-11-11', 1),
       ('initial script', now(), 'roze', 'CHANGE_ME', 'Кузнецов Кирилл Даниилович', '447-986-9003', 'Челябинская область, город Раменское, пр. Гоголя, 05',
        '1992-03-19', 1),
       ('initial script', now(), 'hymie', 'CHANGE_ME', 'Данилова Алина Никитична', '661-788-5395',
        'Орловская область, город Кашира, въезд Бухарестская, 92', '1986-09-02', 1),
       ('initial script', now(), 'selestina', 'CHANGE_ME', 'Волков Андрей Давидович', '153-625-2540',
        'Амурская область, город Волоколамск, проезд Гоголя, 60', '1990-05-19', 1),
       ('initial script', now(), 'arel', 'CHANGE_ME', 'Журавлева Арина Ивановна', '940-208-7181', 'Курская область, город Озёры, наб. Гоголя, 37',
        '1991-08-17', 2),
       ('initial script', now(), 'iago', 'CHANGE_ME', 'Чернов Давид Львович', '120-170-5579', 'Архангельская область, город Зарайск, наб. Сталина, 58',
        '1982-12-20', 2),
       ('initial script', now(), 'goraud', 'CHANGE_ME', 'Давыдова София Юрьевна', '206-801-0274',
        'Рязанская область, город Пушкино, проезд Гагарина, 03', '1950-07-16', 2),
       ('initial script', now(), 'vladimir', 'CHANGE_ME', 'Путин Владимир владимирович', '777-000-0000',
        'Орловская область, город Зарайск, пл. Сталина, 45', '1952-10-07', 3);

insert into gems_types(created_by, created_when, title, carat_weight)
values ('initial script', now(), 'Diamond', 0.11),
       ('initial script', now(), 'Diamond', 0.12),
       ('initial script', now(), 'Diamond', 0.13),
       ('initial script', now(), 'Diamond', 0.14),
       ('initial script', now(), 'Diamond', 0.15),
       ('initial script', now(), 'Diamond', 0.16),
       ('initial script', now(), 'Diamond', 0.17),
       ('initial script', now(), 'Diamond', 0.18),
       ('initial script', now(), 'Diamond', 0.19),
       ('initial script', now(), 'Diamond', 0.20),
       ('initial script', now(), 'Diamond', 0.21),
       ('initial script', now(), 'Diamond', 0.22),
       ('initial script', now(), 'Diamond', 0.23),
       ('initial script', now(), 'Diamond', 0.24),
       ('initial script', now(), 'Diamond', 0.25),
       ('initial script', now(), 'Diamond', 0.26),
       ('initial script', now(), 'Diamond', 0.27),
       ('initial script', now(), 'Diamond', 0.28),
       ('initial script', now(), 'Diamond', 0.29),
       ('initial script', now(), 'Diamond', 0.30),
       ('initial script', now(), 'Diamond', 0.31),
       ('initial script', now(), 'Diamond', 0.32),
       ('initial script', now(), 'Diamond', 0.33),
       ('initial script', now(), 'Diamond', 0.34),
       ('initial script', now(), 'Diamond', 0.35),
       ('initial script', now(), 'Diamond', 0.36),
       ('initial script', now(), 'Diamond', 0.37),
       ('initial script', now(), 'Diamond', 0.38),
       ('initial script', now(), 'Diamond', 0.39),
       ('initial script', now(), 'Diamond', 0.41),
       ('initial script', now(), 'Diamond', 0.42),
       ('initial script', now(), 'Diamond', 0.43),
       ('initial script', now(), 'Diamond', 0.44),
       ('initial script', now(), 'Diamond', 0.45),
       ('initial script', now(), 'Diamond', 0.46),
       ('initial script', now(), 'Diamond', 0.47),
       ('initial script', now(), 'Diamond', 0.48),
       ('initial script', now(), 'Diamond', 0.49),
       ('initial script', now(), 'Diamond', 0.50);

insert into metals_types(created_by, created_when, title)
values ('initial script', now(), 'Red Gold 14K'),
       ('initial script', now(), 'Red Gold 18K'),
       ('initial script', now(), 'White Gold 14K'),
       ('initial script', now(), 'White Gold 18K'),
       ('initial script', now(), 'Yellow Gold 14K'),
       ('initial script', now(), 'Yellow Gold 18K'),
       ('initial script', now(), 'Gold Other'),
       ('initial script', now(), 'Silver 925'),
       ('initial script', now(), 'Silver Other'),
       ('initial script', now(), 'Other Metal');

insert into finished_items(created_by, created_when, item_code, description, metals_info, gems_info)
values ('initial script', now(), 2301, 'Wedding ring, size 15', 'White gold 18K, 3,0g', 'Diamond 3mm, 0.11ct'),
       ('initial script', now(), 2301, 'Wedding ring, size 15.5', 'White gold 18K, 3,3g', 'Diamond 3mm, 0.11ct'),
       ('initial script', now(), 2301, 'Wedding ring, size 16', 'White gold 18K, 3,5g', 'Diamond 3mm, 0.11ct'),
       ('initial script', now(), 2301, 'Wedding ring, size 16.5', 'White gold 18K, 3,7g', 'Diamond 3mm, 0.11ct'),
       ('initial script', now(), 2301, 'Wedding ring, size 17', 'White gold 18K, 3,9g', 'Diamond 3mm, 0.11ct'),
       ('initial script', now(), 2301, 'Wedding ring, size 17.5', 'White gold 18K, 4,1g', 'Diamond 3mm, 0.11ct'),
       ('initial script', now(), 2301, 'Wedding ring, size 18', 'White gold 18K, 4,3g', 'Diamond 3mm, 0.11ct'),
       ('initial script', now(), 2301, 'Wedding ring, size 18.5', 'White gold 18K, 4,5g', 'Diamond 3mm, 0.11ct'),
       ('initial script', now(), 2302, 'Earrings with single diamond', 'White gold 18K, 3,6g', 'Diamond 3.8mm, 0.2ct'),
       ('initial script', now(), 2303, 'Classic wedding ring, size 18', 'Red gold 14K, 4.3g', null),
       ('initial script', now(), 2303, 'Classic wedding ring, size 18.5', 'Red gold 14K, 4.6g', null),
       ('initial script', now(), 2303, 'Classic wedding ring, size 19', 'Red gold 14K, 4.9g', null),
       ('initial script', now(), 2303, 'Classic wedding ring, size 19.5', 'Red gold 14K, 5.2g', null),
       ('initial script', now(), 2303, 'Classic wedding ring, size 20', 'Red gold 14K, 5.5g', null),
       ('initial script', now(), 2303, 'Classic wedding ring, size 20.5', 'Red gold 14K, 5.8g', null),
       ('initial script', now(), 2303, 'Classic wedding ring, size 21', 'Red gold 14K, 6.3g', null),
       ('initial script', now(), 2303, 'Classic wedding ring, size 21.5', 'Red gold 14K, 6.6g', null),
       ('initial script', now(), 2303, 'Classic wedding ring, size 22', 'Red gold 14K, 6.9g', null),
       ('initial script', now(), 2304, 'Nail bracelet', 'Yellow gold 18K, 28g', null),
       ('initial script', now(), 2305, 'Snake ring, size 19', 'Silver 925, 4.5g', null),
       ('initial script', now(), 2306, 'Bracelet with carbon', 'White gold 14K, 24g', '2pcs - Diamond 3mm, 0.15ct'),
       ('initial script', now(), 2307, 'Earrings bean shape', 'Red gold 18K, 5,2g', null);

insert into finished_items_gems_types(finished_item_id, gem_type_id)
values ( 1, 1),
       ( 2, 1),
       ( 3, 1),
       ( 4, 1),
       ( 5, 1),
       ( 6, 1),
       ( 7, 1),
       ( 8, 1),
       ( 9, 10),
       ( 22, 5);

insert into finished_items_metals_types(finished_item_id, metal_type_id) values
(1, 4),
(2, 4),
(3, 4),
(4, 4),
(5, 4),
(6,4),
(7,4),
(8,4),
(9,4),
(10,1),
(11,1),
(12,1),
(13,1),
(14,1),
(15,1),
(16,1),
(17,1),
(18,1),
(19,6),
(20,8),
(21,3),
(22,2);

